"""R2 schema additions: project target auth fields + per-agent cost.

- projects.target_kind: 'copilot_proxy' | 'copilot_internal'
- projects.target_username
- projects.target_password_encrypted (Fernet-encrypted at rest)
- attack_executions.agent_role (so the dashboard can break cost down by role)
- vulnerability_reports.finding_id (so the doc agent can attach to a finding)

Revision ID: 20260512_0004
Revises: 20260512_0003
Create Date: 2026-05-12
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260512_0004"
down_revision: str | None = "20260512_0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "projects",
        sa.Column(
            "target_kind",
            sa.String(32),
            nullable=False,
            server_default="copilot_proxy",
        ),
    )
    op.create_check_constraint(
        "ck_projects_target_kind",
        "projects",
        "target_kind IN ('copilot_proxy','copilot_internal')",
    )
    op.add_column("projects", sa.Column("target_username", sa.String(200), nullable=True))
    op.add_column(
        "projects",
        sa.Column("target_password_encrypted", sa.Text, nullable=True),
    )

    op.add_column(
        "attack_executions",
        sa.Column("agent_role", sa.String(64), nullable=False, server_default=""),
    )

    # Drop the run_id uniqueness so multiple findings per run can each have
    # their own report. The constraint name was autogenerated; inspect
    # information_schema rather than hardcoding.
    op.execute(
        """
        DO $$
        DECLARE
            cname text;
        BEGIN
            SELECT conname INTO cname
            FROM pg_constraint
            WHERE conrelid = 'vulnerability_reports'::regclass
              AND contype = 'u';
            IF cname IS NOT NULL THEN
                EXECUTE 'ALTER TABLE vulnerability_reports DROP CONSTRAINT ' || quote_ident(cname);
            END IF;
        END $$;
        """
    )
    op.add_column(
        "vulnerability_reports",
        sa.Column(
            "finding_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            sa.ForeignKey("findings.id", ondelete="CASCADE"),
            nullable=True,
        ),
    )
    op.create_index(
        "ix_vulnerability_reports_finding_id",
        "vulnerability_reports",
        ["finding_id"],
    )


def downgrade() -> None:
    op.drop_index("ix_vulnerability_reports_finding_id", table_name="vulnerability_reports")
    op.drop_column("vulnerability_reports", "finding_id")
    op.drop_column("attack_executions", "agent_role")
    op.drop_column("projects", "target_password_encrypted")
    op.drop_column("projects", "target_username")
    op.drop_constraint("ck_projects_target_kind", "projects")
    op.drop_column("projects", "target_kind")
